<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\TemplateName.SharedKernel\TemplateName.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\TemplateName.Application.Common\TemplateName.Application.Common.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\TemplateName.Infrastructure.Common\TemplateName.Infrastructure.Common.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\TemplateName.Web.Common\TemplateName.Web.Common.csproj" />
    <ProjectReference Include="..\..\Auth\TemplateName.Modules.Auth.Contracts\TemplateName.Modules.Auth.Contracts.csproj" />
  </ItemGroup>

</Project>
