// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemplateName.Modules.Notifications.Infrastructure.Persistence;

#nullable disable

namespace TemplateName.Modules.Notifications.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    partial class NotificationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notify")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TemplateName.Infrastructure.Common.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Consumer")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("MessageId", "Consumer")
                        .HasName("PK_InboxMessages");

                    b.ToTable("InboxMessages", "notify");
                });

            modelBuilder.Entity("TemplateName.Modules.Notifications.Domain.Deliveries.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<byte>("Channel")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("DeadLetteredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Destination")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("LastError")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LockedUntil")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RenderedSubject")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("SentAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("CreatedAt", "Id")
                        .IsDescending();

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasFilter("[Status] = 0");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "NextAttemptAt"), new[] { "Channel", "LockedUntil" });

                    b.ToTable("Deliveries", "notify");
                });

            modelBuilder.Entity("TemplateName.Modules.Notifications.Domain.HubTickets.HubTicket", b =>
                {
                    b.Property<byte[]>("TokenHash")
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TokenHash");

                    b.ToTable("HubTickets", "notify");
                });

            modelBuilder.Entity("TemplateName.Modules.Notifications.Domain.InApp.InAppNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReadAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasFilter("[ReadAt] IS NULL");

                    b.HasIndex("UserId", "CreatedAt", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("InAppNotifications", "notify");
                });

            modelBuilder.Entity("TemplateName.Modules.Notifications.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<string>("ProtectedData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SourceMessageId", "TypeCode", "RecipientUserId")
                        .IsUnique();

                    b.ToTable("Notifications", "notify");
                });

            modelBuilder.Entity("TemplateName.Modules.Notifications.Domain.Preferences.UserNotificationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "QuietHours", "TemplateName.Modules.Notifications.Domain.Preferences.UserNotificationProfile.QuietHours#QuietHours", b1 =>
                        {
                            b1.Property<TimeOnly>("End")
                                .HasColumnType("time")
                                .HasColumnName("QuietHoursEnd");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("time")
                                .HasColumnName("QuietHoursStart");
                        });

                    b.HasKey("Id");

                    b.ToTable("UserSettings", "notify");
                });

            modelBuilder.Entity("TemplateName.Modules.Notifications.Domain.Preferences.UserPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Channel")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("UserId", "TypeCode", "Channel");

                    b.ToTable("UserPreferences", "notify");
                });

            modelBuilder.Entity("TemplateName.Modules.Notifications.Domain.Deliveries.Delivery", b =>
                {
                    b.HasOne("TemplateName.Modules.Notifications.Domain.Notifications.Notification", null)
                        .WithMany("Deliveries")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TemplateName.Modules.Notifications.Domain.Notifications.Notification", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
